name: Build only for PR

on:
  pull_request:
    branches:
      - "develop"
      - "main"
      - "feature/**"

jobs:
  build-only:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Upgrade yarn
        run: npm install -g yarn

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install modules
        run: yarn bootstrap

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
