name: Check labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, reopened]
    branches:
      - "develop"
      - "main"
      - "feature/*"

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "feature,bugfix,hotfix,release,hotfix"
          banned: "wip"
