name: Pull Request Helper

on:
  pull_request:
    types: [opened]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: a-b-r-o-w-n/check-base-branch-action@v1.1
        if: ${{ !contains(github.head_ref, 'hotfix/') && !contains(github.head_ref, 'develop') && contains(github.base_ref, 'main') }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          protected-branches: "main, develop"
          default-branch: "develop"
          update-branch: true

      - name: Bump version and push tag
        if: ${{ contains(github.head_ref, 'develop') && contains(github.base_ref, 'main') }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: develop
          default_bump: "minor"
          tag_prefix: alpha-v
