name: Release - Canary

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  release-canary:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Upgrade yarn
        run: npm install -g yarn

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Prerelease
        run: yarn release:canary
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  create-release-draft:
    needs: release-canary
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config-canary-patch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
